name: Fullpvp
version: '${project.version}'
main: dev.myclxss.Fullpvp

commands:
  fullpvp:
    description: main command

  join:
    description: join command

  leave:
    description: leave command
  